python transcode.py test/videos/video-01-a.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-b.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-c.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-d.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-e.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-f.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-g.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-h.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-i.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-j.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-k.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-l.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-m.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-n.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-o.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-p.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-01-q.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_1.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_10.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_11.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_12.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_13.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_14.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_15.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_16.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_17.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_18.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_19.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_2.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_20.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_21.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_3.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_4.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_5.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_6.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_7.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_8.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-02-p_9.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_1.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_10.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_11.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_12.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_2.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_3.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_4.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_5.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_6.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_7.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_8.mp4 ~/toneto/transcoded --fps 5
python transcode.py test/videos/video-03-p_9.mp4 ~/toneto/transcoded --fps 5