python scripts/fix_tags.py ~/shan/t-pondered-then-grabbed-1/frames/tagged/tags.json ~/shan/t-pondered-then-grabbed-1/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-a/frames/tagged/tags.json ~/shan/video-01-a/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-b/frames/tagged/tags.json ~/shan/video-01-b/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-c/frames/tagged/tags.json ~/shan/video-01-c/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-d/frames/tagged/tags.json ~/shan/video-01-d/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-e/frames/tagged/tags.json ~/shan/video-01-e/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-f/frames/tagged/tags.json ~/shan/video-01-f/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-g/frames/tagged/tags.json ~/shan/video-01-g/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-h/frames/tagged/tags.json ~/shan/video-01-h/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-i/frames/tagged/tags.json ~/shan/video-01-i/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-j/frames/tagged/tags.json ~/shan/video-01-j/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-k/frames/tagged/tags.json ~/shan/video-01-k/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-l/frames/tagged/tags.json ~/shan/video-01-l/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-m/frames/tagged/tags.json ~/shan/video-01-m/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-n/frames/tagged/tags.json ~/shan/video-01-n/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-o/frames/tagged/tags.json ~/shan/video-01-o/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-p/frames/tagged/tags.json ~/shan/video-01-p/data/tags.json
python scripts/fix_tags.py ~/shan/video-01-q/frames/tagged/tags.json ~/shan/video-01-q/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_1/frames/tagged/tags.json ~/shan/video-02-p_1/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_10/frames/tagged/tags.json ~/shan/video-02-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_11/frames/tagged/tags.json ~/shan/video-02-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_12/frames/tagged/tags.json ~/shan/video-02-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_13/frames/tagged/tags.json ~/shan/video-02-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_14/frames/tagged/tags.json ~/shan/video-02-p_14/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_15/frames/tagged/tags.json ~/shan/video-02-p_15/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_16/frames/tagged/tags.json ~/shan/video-02-p_16/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_17/frames/tagged/tags.json ~/shan/video-02-p_17/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_18/frames/tagged/tags.json ~/shan/video-02-p_18/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_19/frames/tagged/tags.json ~/shan/video-02-p_19/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_2/frames/tagged/tags.json ~/shan/video-02-p_2/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_20/frames/tagged/tags.json ~/shan/video-02-p_20/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_21/frames/tagged/tags.json ~/shan/video-02-p_21/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_3/frames/tagged/tags.json ~/shan/video-02-p_3/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_4/frames/tagged/tags.json ~/shan/video-02-p_4/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_5/frames/tagged/tags.json ~/shan/video-02-p_5/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_6/frames/tagged/tags.json ~/shan/video-02-p_6/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_7/frames/tagged/tags.json ~/shan/video-02-p_7/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_8/frames/tagged/tags.json ~/shan/video-02-p_8/data/tags.json
python scripts/fix_tags.py ~/shan/video-02-p_9/frames/tagged/tags.json ~/shan/video-02-p_9/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_1/frames/tagged/tags.json ~/shan/video-03-p_1/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_10/frames/tagged/tags.json ~/shan/video-03-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_11/frames/tagged/tags.json ~/shan/video-03-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_12/frames/tagged/tags.json ~/shan/video-03-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_2/frames/tagged/tags.json ~/shan/video-03-p_2/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_3/frames/tagged/tags.json ~/shan/video-03-p_3/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_4/frames/tagged/tags.json ~/shan/video-03-p_4/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_5/frames/tagged/tags.json ~/shan/video-03-p_5/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_6/frames/tagged/tags.json ~/shan/video-03-p_6/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_7/frames/tagged/tags.json ~/shan/video-03-p_7/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_8/frames/tagged/tags.json ~/shan/video-03-p_8/data/tags.json
python scripts/fix_tags.py ~/shan/video-03-p_9/frames/tagged/tags.json ~/shan/video-03-p_9/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_1/frames/tagged/tags.json ~/shan/video-04-p_1/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_10/frames/tagged/tags.json ~/shan/video-04-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_11/frames/tagged/tags.json ~/shan/video-04-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_12/frames/tagged/tags.json ~/shan/video-04-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_13/frames/tagged/tags.json ~/shan/video-04-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_14/frames/tagged/tags.json ~/shan/video-04-p_14/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_15/frames/tagged/tags.json ~/shan/video-04-p_15/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_16/frames/tagged/tags.json ~/shan/video-04-p_16/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_17/frames/tagged/tags.json ~/shan/video-04-p_17/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_18/frames/tagged/tags.json ~/shan/video-04-p_18/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_19/frames/tagged/tags.json ~/shan/video-04-p_19/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_2/frames/tagged/tags.json ~/shan/video-04-p_2/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_20/frames/tagged/tags.json ~/shan/video-04-p_20/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_21/frames/tagged/tags.json ~/shan/video-04-p_21/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_3/frames/tagged/tags.json ~/shan/video-04-p_3/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_4/frames/tagged/tags.json ~/shan/video-04-p_4/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_5/frames/tagged/tags.json ~/shan/video-04-p_5/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_6/frames/tagged/tags.json ~/shan/video-04-p_6/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_7/frames/tagged/tags.json ~/shan/video-04-p_7/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_8/frames/tagged/tags.json ~/shan/video-04-p_8/data/tags.json
python scripts/fix_tags.py ~/shan/video-04-p_9/frames/tagged/tags.json ~/shan/video-04-p_9/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_01/frames/tagged/tags.json ~/shan/video-05-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_02/frames/tagged/tags.json ~/shan/video-05-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_03/frames/tagged/tags.json ~/shan/video-05-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_04/frames/tagged/tags.json ~/shan/video-05-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_05/frames/tagged/tags.json ~/shan/video-05-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_06/frames/tagged/tags.json ~/shan/video-05-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_07/frames/tagged/tags.json ~/shan/video-05-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_08/frames/tagged/tags.json ~/shan/video-05-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_09/frames/tagged/tags.json ~/shan/video-05-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_10/frames/tagged/tags.json ~/shan/video-05-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_11/frames/tagged/tags.json ~/shan/video-05-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_12/frames/tagged/tags.json ~/shan/video-05-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_13/frames/tagged/tags.json ~/shan/video-05-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-p_14/frames/tagged/tags.json ~/shan/video-05-p_14/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-t_01/frames/tagged/tags.json ~/shan/video-05-t_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-t_02/frames/tagged/tags.json ~/shan/video-05-t_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-05-t_03/frames/tagged/tags.json ~/shan/video-05-t_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_01/frames/tagged/tags.json ~/shan/video-06-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_02/frames/tagged/tags.json ~/shan/video-06-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_03/frames/tagged/tags.json ~/shan/video-06-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_04/frames/tagged/tags.json ~/shan/video-06-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_05/frames/tagged/tags.json ~/shan/video-06-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_06/frames/tagged/tags.json ~/shan/video-06-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_07/frames/tagged/tags.json ~/shan/video-06-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_08/frames/tagged/tags.json ~/shan/video-06-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_09/frames/tagged/tags.json ~/shan/video-06-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_10/frames/tagged/tags.json ~/shan/video-06-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_11/frames/tagged/tags.json ~/shan/video-06-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_12/frames/tagged/tags.json ~/shan/video-06-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_13/frames/tagged/tags.json ~/shan/video-06-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_14/frames/tagged/tags.json ~/shan/video-06-p_14/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_15/frames/tagged/tags.json ~/shan/video-06-p_15/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_16/frames/tagged/tags.json ~/shan/video-06-p_16/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_17/frames/tagged/tags.json ~/shan/video-06-p_17/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_18/frames/tagged/tags.json ~/shan/video-06-p_18/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_19/frames/tagged/tags.json ~/shan/video-06-p_19/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_20/frames/tagged/tags.json ~/shan/video-06-p_20/data/tags.json
python scripts/fix_tags.py ~/shan/video-06-p_21/frames/tagged/tags.json ~/shan/video-06-p_21/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_01/frames/tagged/tags.json ~/shan/video-07-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_02/frames/tagged/tags.json ~/shan/video-07-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_03/frames/tagged/tags.json ~/shan/video-07-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_04/frames/tagged/tags.json ~/shan/video-07-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_05/frames/tagged/tags.json ~/shan/video-07-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_06/frames/tagged/tags.json ~/shan/video-07-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_07/frames/tagged/tags.json ~/shan/video-07-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_08/frames/tagged/tags.json ~/shan/video-07-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_09/frames/tagged/tags.json ~/shan/video-07-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_11/frames/tagged/tags.json ~/shan/video-07-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_12/frames/tagged/tags.json ~/shan/video-07-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_13/frames/tagged/tags.json ~/shan/video-07-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_14/frames/tagged/tags.json ~/shan/video-07-p_14/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_15/frames/tagged/tags.json ~/shan/video-07-p_15/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_16/frames/tagged/tags.json ~/shan/video-07-p_16/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_17/frames/tagged/tags.json ~/shan/video-07-p_17/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_18/frames/tagged/tags.json ~/shan/video-07-p_18/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_19/frames/tagged/tags.json ~/shan/video-07-p_19/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_20/frames/tagged/tags.json ~/shan/video-07-p_20/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_21/frames/tagged/tags.json ~/shan/video-07-p_21/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_22/frames/tagged/tags.json ~/shan/video-07-p_22/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_23/frames/tagged/tags.json ~/shan/video-07-p_23/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_24/frames/tagged/tags.json ~/shan/video-07-p_24/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_25/frames/tagged/tags.json ~/shan/video-07-p_25/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_26/frames/tagged/tags.json ~/shan/video-07-p_26/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_27/frames/tagged/tags.json ~/shan/video-07-p_27/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_28/frames/tagged/tags.json ~/shan/video-07-p_28/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_29/frames/tagged/tags.json ~/shan/video-07-p_29/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_30/frames/tagged/tags.json ~/shan/video-07-p_30/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_31/frames/tagged/tags.json ~/shan/video-07-p_31/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_32/frames/tagged/tags.json ~/shan/video-07-p_32/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_33/frames/tagged/tags.json ~/shan/video-07-p_33/data/tags.json
python scripts/fix_tags.py ~/shan/video-07-p_34/frames/tagged/tags.json ~/shan/video-07-p_34/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_01/frames/tagged/tags.json ~/shan/video-08-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_02/frames/tagged/tags.json ~/shan/video-08-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_03/frames/tagged/tags.json ~/shan/video-08-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_04/frames/tagged/tags.json ~/shan/video-08-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_05/frames/tagged/tags.json ~/shan/video-08-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_06/frames/tagged/tags.json ~/shan/video-08-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_07/frames/tagged/tags.json ~/shan/video-08-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_08/frames/tagged/tags.json ~/shan/video-08-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_09/frames/tagged/tags.json ~/shan/video-08-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_10/frames/tagged/tags.json ~/shan/video-08-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_11/frames/tagged/tags.json ~/shan/video-08-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_12/frames/tagged/tags.json ~/shan/video-08-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-p_13/frames/tagged/tags.json ~/shan/video-08-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-08-t_01/frames/tagged/tags.json ~/shan/video-08-t_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_01/frames/tagged/tags.json ~/shan/video-09-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_02/frames/tagged/tags.json ~/shan/video-09-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_03/frames/tagged/tags.json ~/shan/video-09-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_04/frames/tagged/tags.json ~/shan/video-09-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_05/frames/tagged/tags.json ~/shan/video-09-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_06/frames/tagged/tags.json ~/shan/video-09-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_07/frames/tagged/tags.json ~/shan/video-09-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_08/frames/tagged/tags.json ~/shan/video-09-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_09/frames/tagged/tags.json ~/shan/video-09-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_10/frames/tagged/tags.json ~/shan/video-09-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_11/frames/tagged/tags.json ~/shan/video-09-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_12/frames/tagged/tags.json ~/shan/video-09-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_13/frames/tagged/tags.json ~/shan/video-09-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_14/frames/tagged/tags.json ~/shan/video-09-p_14/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_15/frames/tagged/tags.json ~/shan/video-09-p_15/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_16/frames/tagged/tags.json ~/shan/video-09-p_16/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_17/frames/tagged/tags.json ~/shan/video-09-p_17/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_18/frames/tagged/tags.json ~/shan/video-09-p_18/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_19/frames/tagged/tags.json ~/shan/video-09-p_19/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_20/frames/tagged/tags.json ~/shan/video-09-p_20/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_21/frames/tagged/tags.json ~/shan/video-09-p_21/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_22/frames/tagged/tags.json ~/shan/video-09-p_22/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_23/frames/tagged/tags.json ~/shan/video-09-p_23/data/tags.json
python scripts/fix_tags.py ~/shan/video-09-p_24/frames/tagged/tags.json ~/shan/video-09-p_24/data/tags.json
python scripts/fix_tags.py ~/shan/video-10-t_01/frames/tagged/tags.json ~/shan/video-10-t_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-12-t_01/frames/tagged/tags.json ~/shan/video-12-t_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_01/frames/tagged/tags.json ~/shan/video-13-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_02/frames/tagged/tags.json ~/shan/video-13-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_03/frames/tagged/tags.json ~/shan/video-13-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_04/frames/tagged/tags.json ~/shan/video-13-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_05/frames/tagged/tags.json ~/shan/video-13-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_06/frames/tagged/tags.json ~/shan/video-13-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_07/frames/tagged/tags.json ~/shan/video-13-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_08/frames/tagged/tags.json ~/shan/video-13-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_09/frames/tagged/tags.json ~/shan/video-13-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_10/frames/tagged/tags.json ~/shan/video-13-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_11/frames/tagged/tags.json ~/shan/video-13-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_12/frames/tagged/tags.json ~/shan/video-13-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-13-p_13/frames/tagged/tags.json ~/shan/video-13-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_01/frames/tagged/tags.json ~/shan/video-16-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_02/frames/tagged/tags.json ~/shan/video-16-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_03/frames/tagged/tags.json ~/shan/video-16-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_04/frames/tagged/tags.json ~/shan/video-16-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_05/frames/tagged/tags.json ~/shan/video-16-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_06/frames/tagged/tags.json ~/shan/video-16-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_07/frames/tagged/tags.json ~/shan/video-16-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_08/frames/tagged/tags.json ~/shan/video-16-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_09/frames/tagged/tags.json ~/shan/video-16-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_10/frames/tagged/tags.json ~/shan/video-16-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_11/frames/tagged/tags.json ~/shan/video-16-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_12/frames/tagged/tags.json ~/shan/video-16-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_13/frames/tagged/tags.json ~/shan/video-16-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_14/frames/tagged/tags.json ~/shan/video-16-p_14/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_15/frames/tagged/tags.json ~/shan/video-16-p_15/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_16/frames/tagged/tags.json ~/shan/video-16-p_16/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_17/frames/tagged/tags.json ~/shan/video-16-p_17/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_18/frames/tagged/tags.json ~/shan/video-16-p_18/data/tags.json
python scripts/fix_tags.py ~/shan/video-16-p_19/frames/tagged/tags.json ~/shan/video-16-p_19/data/tags.json
python scripts/fix_tags.py ~/shan/video-17-t_01/frames/tagged/tags.json ~/shan/video-17-t_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_01/frames/tagged/tags.json ~/shan/video-20-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_02/frames/tagged/tags.json ~/shan/video-20-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_03/frames/tagged/tags.json ~/shan/video-20-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_04/frames/tagged/tags.json ~/shan/video-20-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_05/frames/tagged/tags.json ~/shan/video-20-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_06/frames/tagged/tags.json ~/shan/video-20-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_07/frames/tagged/tags.json ~/shan/video-20-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_08/frames/tagged/tags.json ~/shan/video-20-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_09/frames/tagged/tags.json ~/shan/video-20-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_10/frames/tagged/tags.json ~/shan/video-20-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_11/frames/tagged/tags.json ~/shan/video-20-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_12/frames/tagged/tags.json ~/shan/video-20-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_13/frames/tagged/tags.json ~/shan/video-20-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_14/frames/tagged/tags.json ~/shan/video-20-p_14/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_15/frames/tagged/tags.json ~/shan/video-20-p_15/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_16/frames/tagged/tags.json ~/shan/video-20-p_16/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_17/frames/tagged/tags.json ~/shan/video-20-p_17/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_18/frames/tagged/tags.json ~/shan/video-20-p_18/data/tags.json
python scripts/fix_tags.py ~/shan/video-20-p_19/frames/tagged/tags.json ~/shan/video-20-p_19/data/tags.json
python scripts/fix_tags.py ~/shan/video-21-p_01/frames/tagged/tags.json ~/shan/video-21-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-21-p_02/frames/tagged/tags.json ~/shan/video-21-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-21-p_03/frames/tagged/tags.json ~/shan/video-21-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-21-p_04/frames/tagged/tags.json ~/shan/video-21-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-21-p_05/frames/tagged/tags.json ~/shan/video-21-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-21-p_06/frames/tagged/tags.json ~/shan/video-21-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-21-p_07/frames/tagged/tags.json ~/shan/video-21-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-21-p_08/frames/tagged/tags.json ~/shan/video-21-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_01/frames/tagged/tags.json ~/shan/video-23-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_02/frames/tagged/tags.json ~/shan/video-23-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_03/frames/tagged/tags.json ~/shan/video-23-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_04/frames/tagged/tags.json ~/shan/video-23-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_05/frames/tagged/tags.json ~/shan/video-23-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_06/frames/tagged/tags.json ~/shan/video-23-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_07/frames/tagged/tags.json ~/shan/video-23-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_08/frames/tagged/tags.json ~/shan/video-23-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_09/frames/tagged/tags.json ~/shan/video-23-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_10/frames/tagged/tags.json ~/shan/video-23-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-23-p_11/frames/tagged/tags.json ~/shan/video-23-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_01/frames/tagged/tags.json ~/shan/video-24-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_02/frames/tagged/tags.json ~/shan/video-24-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_03/frames/tagged/tags.json ~/shan/video-24-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_04/frames/tagged/tags.json ~/shan/video-24-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_05/frames/tagged/tags.json ~/shan/video-24-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_06/frames/tagged/tags.json ~/shan/video-24-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_07/frames/tagged/tags.json ~/shan/video-24-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_08/frames/tagged/tags.json ~/shan/video-24-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_09/frames/tagged/tags.json ~/shan/video-24-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_10/frames/tagged/tags.json ~/shan/video-24-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_11/frames/tagged/tags.json ~/shan/video-24-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_12/frames/tagged/tags.json ~/shan/video-24-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_13/frames/tagged/tags.json ~/shan/video-24-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-24-p_14/frames/tagged/tags.json ~/shan/video-24-p_14/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_01/frames/tagged/tags.json ~/shan/video-29-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_02/frames/tagged/tags.json ~/shan/video-29-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_03/frames/tagged/tags.json ~/shan/video-29-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_04/frames/tagged/tags.json ~/shan/video-29-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_05/frames/tagged/tags.json ~/shan/video-29-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_06/frames/tagged/tags.json ~/shan/video-29-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_07/frames/tagged/tags.json ~/shan/video-29-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_08/frames/tagged/tags.json ~/shan/video-29-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_09/frames/tagged/tags.json ~/shan/video-29-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_10/frames/tagged/tags.json ~/shan/video-29-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_11/frames/tagged/tags.json ~/shan/video-29-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_12/frames/tagged/tags.json ~/shan/video-29-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-29-p_13/frames/tagged/tags.json ~/shan/video-29-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-31-p_01/frames/tagged/tags.json ~/shan/video-31-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-31-p_02/frames/tagged/tags.json ~/shan/video-31-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-31-p_03/frames/tagged/tags.json ~/shan/video-31-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-31-p_04/frames/tagged/tags.json ~/shan/video-31-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-31-p_05/frames/tagged/tags.json ~/shan/video-31-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-31-p_06/frames/tagged/tags.json ~/shan/video-31-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-31-p_07/frames/tagged/tags.json ~/shan/video-31-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-31-p_08/frames/tagged/tags.json ~/shan/video-31-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-33-p_02/frames/tagged/tags.json ~/shan/video-33-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-33-p_03/frames/tagged/tags.json ~/shan/video-33-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-33-p_05/frames/tagged/tags.json ~/shan/video-33-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-39-p_01/frames/tagged/tags.json ~/shan/video-39-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-39-p_02/frames/tagged/tags.json ~/shan/video-39-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-39-p_03/frames/tagged/tags.json ~/shan/video-39-p_03/data/tags.json
python scripts/fix_tags.py ~/shan/video-39-p_04/frames/tagged/tags.json ~/shan/video-39-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-39-p_05/frames/tagged/tags.json ~/shan/video-39-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-39-p_06/frames/tagged/tags.json ~/shan/video-39-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-39-p_07/frames/tagged/tags.json ~/shan/video-39-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-39-p_08/frames/tagged/tags.json ~/shan/video-39-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-39-p_09/frames/tagged/tags.json ~/shan/video-39-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_01/frames/tagged/tags.json ~/shan/video-42-p_01/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_02/frames/tagged/tags.json ~/shan/video-42-p_02/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_04/frames/tagged/tags.json ~/shan/video-42-p_04/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_05/frames/tagged/tags.json ~/shan/video-42-p_05/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_06/frames/tagged/tags.json ~/shan/video-42-p_06/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_07/frames/tagged/tags.json ~/shan/video-42-p_07/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_08/frames/tagged/tags.json ~/shan/video-42-p_08/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_09/frames/tagged/tags.json ~/shan/video-42-p_09/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_10/frames/tagged/tags.json ~/shan/video-42-p_10/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_11/frames/tagged/tags.json ~/shan/video-42-p_11/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_12/frames/tagged/tags.json ~/shan/video-42-p_12/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_13/frames/tagged/tags.json ~/shan/video-42-p_13/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_14/frames/tagged/tags.json ~/shan/video-42-p_14/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_15/frames/tagged/tags.json ~/shan/video-42-p_15/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_16/frames/tagged/tags.json ~/shan/video-42-p_16/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_17/frames/tagged/tags.json ~/shan/video-42-p_17/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_18/frames/tagged/tags.json ~/shan/video-42-p_18/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_19/frames/tagged/tags.json ~/shan/video-42-p_19/data/tags.json
python scripts/fix_tags.py ~/shan/video-42-p_20/frames/tagged/tags.json ~/shan/video-42-p_20/data/tags.json